### PR TITLE
feat: Support AWS provider 4

### PR DESCRIPTION
**Pull request by npalm**
See also #44

### CODE REVIEW

**Comment by npalm** [comment]
@meMuszr At the moment I got a change every time I apply:

```
  # module.runner.module.cache.aws_s3_bucket_lifecycle_configuration.build_cache_versioning[0] will be updated in-place
  ~ resource "aws_s3_bucket_lifecycle_configuration" "build_cache_versioning" {
        id     = "12345678900-gitlab-runner-cache"
        # (1 unchanged attribute hidden)

      ~ rule {
            id     = "clear"
            # (1 unchanged attribute hidden)

          ~ expiration {
              ~ expired_object_delete_marker = false -> true
                # (1 unchanged attribute hidden)
            }

            # (1 unchanged block hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

**Comment by npalm** [comment]
> @meMuszr At the moment I got a change every time I apply:
> 
> ```
>   # module.runner.module.cache.aws_s3_bucket_lifecycle_configuration.build_cache_versioning[0] will be updated in-place
>   ~ resource "aws_s3_bucket_lifecycle_configuration" "build_cache_versioning" {
>         id     = "12345678900-gitlab-runner-cache"
>         # (1 unchanged attribute hidden)
> 
>       ~ rule {
>             id     = "clear"
>             # (1 unchanged attribute hidden)
> 
>           ~ expiration {
>               ~ expired_object_delete_marker = false -> true
>                 # (1 unchanged attribute hidden)
>             }
> 
>             # (1 unchanged block hidden)
>         }
>     }
> 
> Plan: 0 to add, 1 to change, 0 to destroy.
> ```

solved

**Comment by meMuszr** [comment]
Hey - just a heads up - this doesn't work on 4.6 and 4.0. Pinned to 4.2 and it ran fine. Didn't really investigate further.
4.6 was erroring on ASG launch template's network interface device index.
4.0 was erroring on cache resource "aws_s3_bucket_lifecycle_configuration" filter

**Comment by npalm** [comment]
> Hey - just a heads up - this doesn't work on 4.6 and 4.0. Pinned to 4.2 and it ran fine. Didn't really investigate further. 4.6 was erroring on ASG launch template's network interface device index. 4.0 was erroring on cache resource "aws_s3_bucket_lifecycle_configuration" filter

Just tested with 4.7 and 4.9 all works fine

**Comment by kayman-mk** [comment]
Any chance to push this one? Just tested the `runner-docker` example with AWS provider 4.13. Everything fine. My jobs were processed.

**Comment by npalm** [comment]
Sorry for all the delay, first syncing most PR's. Next merge this breaking change.

**Comment by npalm** [comment]
PR is ready. Will update later this week the README and a notice of the upgrade and relase a new major version

**Comment by npalm** [comment]
@kayman-mk this PR is finally ready. Will run tomorrow or Saturday one more last check. Next will run a reease.

**Pull request merged**
