### PR TITLE
refactor: Terraform AWS Provider Version 4 Upgrade

### PR DESCRIPTION
**Pull request by meMuszr**
Followed upgrade guide according to:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade#s3-bucket-refactor

## Description

Update to version 4 of the AWS provider

### CODE REVIEW

**Comment by MarcMeszaros** [comment]
@meMuszr Tried using the pull request branch and get these errors (from a Terraform Cloud speculative run using provider version `~> 3.74`):

```
╷
│ Error: Invalid resource type
│ 
│   on .terraform/modules/gitlab_ondemand/modules/cache/main.tf line 37, in resource "aws_s3_bucket_acl" "build_cache_acl":
│   37: resource "aws_s3_bucket_acl" "build_cache_acl" {
│ 
│ The provider hashicorp/aws does not support resource type
│ "aws_s3_bucket_acl".
╵
╷
│ Error: Invalid resource type
│ 
│   on .terraform/modules/gitlab_ondemand/modules/cache/main.tf line 44, in resource "aws_s3_bucket_versioning" "build_cache_versioning":
│   44: resource "aws_s3_bucket_versioning" "build_cache_versioning" {
│ 
│ The provider hashicorp/aws does not support resource type
│ "aws_s3_bucket_versioning".
╵
╷
│ Error: Invalid resource type
│ 
│   on .terraform/modules/gitlab_ondemand/modules/cache/main.tf line 53, in resource "aws_s3_bucket_lifecycle_configuration" "build_cache_versioning":
│   53: resource "aws_s3_bucket_lifecycle_configuration" "build_cache_versioning" {
│ 
│ The provider hashicorp/aws does not support resource type
│ "aws_s3_bucket_lifecycle_configuration".
╵
╷
│ Error: Invalid resource type
│ 
│   on .terraform/modules/gitlab_ondemand/modules/cache/main.tf line 72, in resource "aws_s3_bucket_server_side_encryption_configuration" "build_cache_encryption":
│   72: resource "aws_s3_bucket_server_side_encryption_configuration" "build_cache_encryption" {
│ 
│ The provider hashicorp/aws does not support resource type
│ "aws_s3_bucket_server_side_encryption_configuration".

```

I suspect this might have to be a breaking change and bump the minimum provider version.

**Comment by meMuszr** [comment]
You're right. Thought these were just breaking changes but existing resources. Docs show that it got introduced in >=4.0

**Comment by npalm** [comment]
@meMuszr thanks for the PR will check the PR this weekend. Maybe I will push a temporary fix before mering to lock the pvovider on 3*

**Comment by npalm** [comment]
Most likely you also need to run `terraform init -upgrade` on the examples to update the AWS provider in de lock file

**Comment by meMuszr** [comment]
Will update shortly

**Comment by npalm** [comment]
Merged in #460

**Pull request closed without merging**
