### PR TITLE
Remove the null_data_source (#332)

### PR DESCRIPTION
**Pull request by kayman-mk**
## Description

As described in #332 `null_data_source` can be replaced by locals to avoid the warning message during plan/apply.

## Migrations required

NO

## Verification

Checking the tags output in the plan:
```
      + tags                      = [
          + {
              + "key"                 = "Environment"
              + "propagate_at_launch" = "true"
              + "value"               = "prod-gitlab-ci-runner-terraform"
            },
          + {
              + "key"                 = "Name"
              + "propagate_at_launch" = "true"
              + "value"               = "Gitlab Runner Terraform Agent"
            },
          + {
              + "key"                 = "allowReadPlatformCredentials"
              + "propagate_at_launch" = "true"
              + "value"               = "gitlab-ci-runner"
            },
          + {
              + "key"                 = "app"
              + "propagate_at_launch" = "true"
              + "value"               = "runner"
            },
          + {
              + "key"                 = "environment"
              + "propagate_at_launch" = "true"
              + "value"               = "prod"
            },
          + {
              + "key"                 = "service"
              + "propagate_at_launch" = "true"
              + "value"               = "gitlab-ci"
            },
          + {
              + "key"                 = "team"
              + "propagate_at_launch" = "true"
              + "value"               = "sales"
            },
        ]
```

### CODE REVIEW

**Comment by kayman-mk** [comment]
@npalm Seems that the pipeline is broken. Complaining about Terraform versions. Could you please check this?

**Comment by kayman-mk** [comment]
> @npalm Seems that the pipeline is broken. Complaining about Terraform versions. Could you please check this?

Was a version constraint in the "key" module. Fixed.

**Comment by npalm** [comment]
thanks, will check the PR in the next days, sorry for the delay

**Review by npalm — APPROVED** [review]
Thanks!

**Pull request merged**
