### PR TITLE
docs: detail the usage of S3 cache policy

### PR DESCRIPTION
**Pull request by kayman-mk**
## Description

As explained in #410 and #426 additional documentation is needed for
- permissions needed to access the S3 cache. This is configured on the Runner instance and not on the Executor (as I thought too). But the documentation tolds a different story.

## Migrations required

No

## Verification

Just some comments. No verification done.

## Documentation

We use [pre-commit](https://pre-commit.com/) to update the Terraform inputs and outputs in the documentation via [terraform-docs](https://github.com/terraform-docs/terraform-docs). Ensure you have installed those components.

### CODE REVIEW

**Review by npalm — APPROVED** [review]
@kayman-mk looks good, but I assume you would like to got it merged after #410 Since the adpater is not supported yet

**Comment by kayman-mk** [comment]
@npalm Can be merged immediately I think as #410 is closed and works as documented by the Gitlab Runner team.

**Comment by npalm** [comment]
@kayman-mk #410 is closed and not merged. Looks like the gitlab documentation is a bit misleading.

**Comment by npalm** [comment]
@kayman-mk can we close this?

**Comment by kayman-mk** [comment]
@npalm Think it would be useful to have the comment regarding the instance profile for S3 bucket access in the code. The `null_resource` will be deleted soon. You may close this PR if you think we can go without it, yes.

**Comment by kayman-mk** [comment]
@npalm Merged the `develop` branch and removed half of the documentation as the code was deleted. There is only one remark left regarding the S3 policies. Merge or close? I don't care, but as there were problems in the past, I think it would be useful to have this remark in the code.

**Comment by npalm** [comment]
On my list for Monday, thx for the work

**Comment by kayman-mk** [comment]
@npalm Branch updated

**Comment by kayman-mk** [comment]
Argh, the base branch was still `develop` and not main. Will create a new PR.

**Pull request merged**
