### PR TITLE
Add IAM policies for runner as variable

### LINKED ISSUE #155: Pass IAM policies ARNs as a list to an input variable
It would be much more convenient if one could reuse existing IAM policies (custom or managed) and just pass a list of ARNs that would be attached to the Runner's roles

### PR DESCRIPTION
**Pull request by kayman-mk**
## Description
Add a new variable to add a list of policies to be added to the runner's role.

Closes #155 

## Migrations required
No

## Verification
No verification done. I have no cloud account at hand.

## Documentation
Documentation updated.

### CODE REVIEW

**Comment by npalm** [comment]
@kayman-mk nice work, stil work in progress?

**Comment by kayman-mk** [comment]
Should be complete. Anything you miss? May be the verification. But I have no cloud account I could use for this.

**Comment by npalm** [comment]
The PR is still on draft, so if you are finished please mark the PR as done so it can be merged

**Comment by kayman-mk** [comment]
Oh, I didn't see it in the github app. Fixed.

**Pull request merged**
