### PR TITLE
Feature/allow multilines build scripts

### PR DESCRIPTION
**Pull request by fpalluel**
## Description
See https://github.com/npalm/terraform-aws-gitlab-runner/issues/281

### CODE REVIEW

**Comment by npalm** [comment]
Will check asap

**Comment by npalm** [comment]
Did a quick check on the default example. Instance is created but agent does NOT start. In complaints about the pre en post build script. Seem the multi line proposal is not working. I had not the time to dig in further. Hope you have an idea how to fix it.

**Comment by fpalluel** [comment]
Hello,
Sorry, I was so focused with the multiline case, that I made a mistake with the single case !

In the example:
` runners_post_build_script = "echo 'single line'"`

should be:
` runners_post_build_script = "\"echo 'single line'\""`

which is, admittedly, ugly, but I cannot see any other mean to make both single and multilines cases work :-(
If you agree with this syntax, I'll fix the PR at once.

**Comment by npalm** [comment]
Sorry for the late response, will check later today.

**Comment by npalm** [comment]
Adding ref to gitlab docs: https://docs.gitlab.com/runner/configuration/advanced-configuration.html

**Comment by npalm** [comment]
> Hello,
> Sorry, I was so focused with the multiline case, that I made a mistake with the single case !
> 
> In the example:
> ` runners_post_build_script = "echo 'single line'"`
> 
> should be:
> ` runners_post_build_script = "\"echo 'single line'\""`
> 
> which is, admittedly, ugly, but I cannot see any other mean to make both single and multilines cases work :-(
> If you agree with this syntax, I'll fix the PR at once.

LGTM

**Comment by npalm** [comment]
@fpalluel did you had time to have a look on the PR?

**Comment by fpalluel** [comment]
> @fpalluel did you had time to have a look on the PR?

Hello, just did it, sorry for the delay ;-)

**Review by npalm — CHANGES_REQUESTED** [review]
All good, please can you rebase the PR?

**Comment by fpalluel** [comment]
Locally on MacOs I run : 
* Terraform v0.14.5
* Terraform-docs version v0.11.0
* TFLint version 0.22.0

And the pre-commit hook execution leads to differences in generated Terraform docs

**Comment by npalm** [comment]
> Locally on MacOs I run :
> 
> * Terraform v0.14.5
> * Terraform-docs version v0.11.0
> * TFLint version 0.22.0
> 
> And the pre-commit hook execution leads to differences in generated Terraform docs

Seems missing in the docs, but the moduel is still on terraform 13. I use tfenv to swithc terraform version. Can you try the pre-commit hooks with terraform 13. In case the troubles remain, I can do a local merge

**Comment by fpalluel** [comment]
Hello,
I just tried with Terraform 13.6, but the issue seems to be with Terraform-docs 0.11.0 (see [releases](https://github.com/terraform-docs/terraform-docs/releases)). The latest release brings some changes in the generated content, adding some sections.

So I switched back to Terraform-docs 0.10.1, but there are still changes in the generated content (headers formatting for instance)...
I don't know why, but I cannot reproduce the generated content formatting of the `develop` branch.

**Review by npalm — APPROVED** [review]

**Pull request merged**
