### PR TITLE
feat: add amazon-ecr-credential-helper inside userdata_pre_install

### PR DESCRIPTION
**Pull request by dmitrijn**
closes: 
https://github.com/npalm/terraform-aws-gitlab-runner/issues/271
https://github.com/npalm/terraform-aws-gitlab-runner/pull/308

## Description
feat: add amazon-ecr-credential-helper inside userdata_pre_install
chore: update pre-commit-terraform and readme.md to latest version

### CODE REVIEW

**Comment by dmitrijn** [comment]
@npalm could you check?

**Comment by npalm** [comment]
@dmitrijn thanks for the reminder, will run a check later this week

**Review by npalm — APPROVED** [review]
@dmitrijn thanks for the contribution! LGTM will be merged

**Comment by vikassach** [comment]
A quick question guys, will this work on ubuntu or debian based systems ? Should the script not check if its ec2 linux and then do yum install ?

**Pull request merged**
