### PR TITLE
Add instance profile to spot instances and auto register

### PR DESCRIPTION
**Pull request by PatrickWolleb**
Provides better security by adding instance profiles to docker machine command in config.toml.
Provides better developer experience by adding gitlab registration command in user-data.
Provides capability of adding additional docker volume mounts

### CODE REVIEW

**Comment by PatrickWolleb** [comment]
Great @npalm, thanks.
It is still needs finalising. Testing different configs.

**Comment by npalm** [comment]
> Great @npalm, thanks.
> It is still needs finalising. Testing different configs.

@PatrickWolleb did you was able to finish testing?

**Comment by PatrickWolleb** [comment]
I am have new approach of storing the runner token Secure Param. Store. I will try to finalise over Christmas.

**Comment by npalm** [comment]
@PatrickWolleb Thx!

**Pull request closed without merging**
