### PR TITLE
Upgrade to Terraform 13

### PR DESCRIPTION
**Pull request by npalm**
## Description
Upgrade to terraform 13

## Migrations required
NO

## Verification
example-default

### CODE REVIEW

**Comment by kayman-mk** [comment]
Not sure if it is a little bit too early. I tried using 0.13 for our infrastructure and got many errors when creating the plan. Seems to me that 0.13 is unstable for now.

**Comment by npalm** [comment]
I ran a full upgrade from 12 to 13 for the default example. So far so good and no strange errors. For now I am not planning directly to merge this back to develop but leave a a few weeks aside. Since no terraform 13 feature is used by the module, the module still works with 12.

**Comment by npalm** [comment]
Will check my PR later this week to see if I can merge it back.

**Comment by Fuuzetsu** [comment]
Terraform 14 is out now.

**Pull request merged**
