### PR TITLE
Added ability to specify runners to use public subnet

### PR DESCRIPTION
**Pull request by Andrew8xx8**

### CODE REVIEW

**Comment by PanfilovDenis** [comment]
+1 I need it. It can really save your money.

**Comment by npalm** [comment]
Thanks for the contribution!

**Comment by PanfilovDenis** [comment]
@npalm Cool! Thank you a lot! Could you bump the version of the module on registry.terraform.io ?

**Comment by npalm** [comment]
@PanfilovDenis done, release 1.3.0 is available

**Pull request merged**
