### PR TITLE
Allow ping to runners and agent from cidr range

### PR DESCRIPTION
**Pull request by fliphess**
## Description
this addition is for debugging purposes: Allow icmp ping traffic to the agent and runners from the list of allowed cidr ranges.

## Migrations required
NO

## Verification
Running this branch in production currently. Our situation is a copy from example-public

## Documentation
Added the `enable_ping` variable to the documentation in `_docs/`

### CODE REVIEW

**Comment by fliphess** [comment]
I'd prefer to move the security groups to it's own file: `security_groups.tf`, please let me know you think that's a good idea, than I'll add another commit accomplishing this.

**Comment by npalm** [comment]
@fliphess thanks, will check soon

**Comment by fliphess** [comment]
👍 No hurries :)

**Comment by npalm** [comment]
@fliphess thanks!

**Pull request merged**
