### PR TITLE
Encryption security issues

### PR DESCRIPTION
**Pull request by hendrixroa**
## Description
Enable ebs encryption option, default:false

## Migrations required
NO

## Verification
NO

## Documentation
The docs are updated successfully with new variables description

### CODE REVIEW

**Comment by hendrixroa** [comment]
TODO:
- user data encryption

**Comment by bishtawi** [comment]
Does the MR as it is now complete the task of enabling encryption on the root EBS? If it does, can we merge this as it is now, and create a separate MR for encrypting user data (where does that exist, if not in the root device)? I only ask because I am looking to enable encryption on the EBS and it would be nice to get that in, if it really is just a single boolean. If the boolean by itself does nothing, and it requires additional work for it to actually encrypt, then carry on.

**Comment by npalm** [comment]
@hendrixroa any update on this PR? Are you still working on it?

**Comment by hendrixroa** [comment]
@npalm Yes, I'm testing with some security tools with this module, getting some insights from `scout-suite`

**Comment by hendrixroa** [comment]
@npalm  I don't underatand why variables.tf has conflicts, can you review it pls?

**Comment by npalm** [comment]
@hendrixroa I was not able to run the default example. I have made some comments. Please can you update the default example to so it works with KMS encryption. It looks like the changes in the cache module are missing. As well configuration for cloudwatch to grant access to the KMS keuy

**Comment by npalm** [comment]
@hendrixroa inspired by this PR I have created a slightly different approach for the log encryption. Please could you have a look at PR #156

**Comment by hendrixroa** [comment]
@npalm that is the right way to go, the encryption should be optional.

**Pull request closed without merging**
