### PR TITLE
feat!: Add variable for Docker registry mirror

### LINKED ISSUE #270: Support for Docker Hub registry mirror for rate-limited pulls
While running some automation jobs in bulk on my Gitlab projects, I got hit today by the infamous new [Docker Hub Rate Limiting](https://www.docker.com/increase-rate-limits)...

```
Waiting for services to be up and running...
Pulling docker image docker:latest ...
ERROR: Preparation failed: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit (docker.go:142:0s)
``` 

There are some solutions to this problem:
* **Authenticate to docker hub**. Anonymously you get 100 container image requests per 6 hours, with an authenticated account you get 200 container image requests per 6 hours. 
* **Pay for Docker Hub**. There's a [Pro account](https://www.docker.com/pricing) already for only $5/month. Requires you to authenticate. For a company, this is the easiest solution and makes the most sense to pay for such a critical service. In my case, it's a personal project for fun so worth looking for other (cheaper) ways. 
* **Cache on GitLab container registry**: tag and push the docker hub image you use (e.g. `php:8`) to your Gitlab repository container registry to "cache", and simply pull from that one to decrease pulls from docker hub. Bit tedious... 
* Use the free [**Gitlab Dependency Proxy**](https://docs.gitlab.com/ee/user/packages/dependency_proxy/) 
  * Requires you to add a `docker login` statement and to prefix every docker image with `$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX`. Currently, I tried this but get a 500 error back on `docker pull`...
* **Self-Hosted Docker Registry As Pull-Through Cache**:  [Docker Hub Registry Mirror](https://docs.gitlab.com/runner/configuration/speed_up_job_execution.html#docker-hub-registry-mirror) and let the runner use this as a registry as a pull-through cache. A similar thing can be done with JFrog Artifactory/Container Registry. Because distribution uses HEAD manifest requests to check if cached content has changed, it will not count towards the rate limit. Note that initial requests for Hub images that are not yet in cache will be counted.
* Google and AWS have both launched a solution: https://cloud.google.com/container-registry/docs/pulling-cached-images and https://aws.amazon.com/blogs/containers/advice-for-customers-dealing-with-docker-hub-rate-limits-and-a-coming-soon-announcement/ and https://aws.amazon.com/blogs/aws/amazon-ecr-public-a-new-public-container-registry/

Does anyone have experience with any of these solutions? Did anyone try the self-hosted Docker registry mirror? Would it make sense to spin it up in this repo, or provide config options in this repo to add it?

### PR DESCRIPTION
**Pull request by kayman-mk**
## Description

As [Docker](https://docs.docker.com/docker-hub/download-rate-limit/) introduced rate limiting we should set a Docker registry mirror. This was possible via `docker_machine_options`. I think it makes sense to make this explicit using a dedicated variable.

Solves a part of #393 
Closes #270 

## Migrations required

Yes, if the option `engine-registry-mirror` is used within the `docker_machine_options`. If so move the mirror URL to the new variable `runners_docker_registry_mirror`

## Verification

Checked all combinations of `runners_docker_registry_mirror` and `docker_machine_options`.

## Documentation

We use [pre-commit](https://pre-commit.com/) to update the Terraform inputs and outputs in the documentation via [terraform-docs](https://github.com/terraform-docs/terraform-docs). Ensure you have installed those components.

### CODE REVIEW

**Comment by npalm** [comment]
@kayman-mk is this PR still work in progress? If yes can you set it in the draft mode?

**Comment by kayman-mk** [comment]
@npalm Verification still missing. It shows Draft here?!

**Review by npalm — APPROVED** [review]
LGTM, still in draft?

**Comment by kayman-mk** [comment]
Yes, unfortunately. The code looks good to me, but is not working. Leaving the registry mirror empty also removes the all docker machine options from the `config.toml`. And I have no idea, why?!

**Comment by npalm** [comment]
OK will try to check also, do you have an example config?

**Comment by kayman-mk** [comment]
Sure. I use one of my other runners and manipulate the config as follows:
* `docker_machine_options = ["a=b", "b=c]`
* `runners_docker_registry_mirror` remains unset

The docker_machine_options will not appear in the config file.

**Comment by kayman-mk** [comment]
Just tested with 
* `docker_machine_options` unset
* `runners_docker_registry_mirror = "https://xxx/"`

No docker_machine_options in config.toml

**Comment by kayman-mk** [comment]
@npalm Found it. Checked all 4 settings for the 2 variables.

**Review by npalm — APPROVED** [review]
LGTM,

**Comment by npalm** [comment]
Need only to run a test asap

**Comment by npalm** [comment]
Tested

- [ ] default example
- [ ] default example with mirror to gcr

**Comment by npalm** [comment]
> Tested
> 
> * [x]  default example
> * [x]  default example with mirror to gcr

Checked on the agent instance, config looks proper. Not good way to test the mirror was used at all.

**Pull request merged**
