### PR TITLE
chore(ci): Add tfdocs update to workflow

### PR DESCRIPTION
**Pull request by npalm**
## Description

Auto update tf-docs. Fix for #423 

## Migrations required

No

## Verification

n/a

### CODE REVIEW

**Comment by kayman-mk** [comment]
@npalm Try the configuration below. Put the workflow fails with missing permissions during `git push`:
```
M  README.md
M  examples/runner-default/README.md
M  examples/runner-docker/README.md
M  examples/runner-pre-registered/README.md
M  examples/runner-public/README.md
[auto-update-tfdocs 5b3d4cb] terraform-docs: automated action
 5 files changed, 167 insertions(+), 77 deletions(-)
remote: Permission to npalm/terraform-aws-gitlab-runner.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/npalm/terraform-aws-gitlab-runner/': The requested URL returned error: 403
```

```hcl
      - name: Terraform Docs
        uses: terraform-docs/gh-actions@main
        with:
          #working-dir: .
          find-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
```

Version 0.11.0 is not running. See https://github.com/terraform-docs/gh-actions/issues/73

**Comment by kayman-mk** [comment]
Perhaps it's better to generate the docs during the release cycle only and not for every commit in a PR?

**Comment by npalm** [comment]
Thanks for help. Only updating in the release flow is maybe easier, but will result in an not up-to-date develop branch.

**Comment by kayman-mk** [comment]
Oh yes, of course. Wasn't aware of the develop branch.

**Comment by npalm** [comment]
Need to find a bit of time later this week. Have similar issues on other projects as well

**Comment by npalm** [comment]
Closing, solving in #466

**Pull request closed without merging**
