### PR TITLE
ci: scan Terraform code for potential security risks

### PR DESCRIPTION
**Pull request by kayman-mk**
## Description

Introduce a TfSec scan (see https://github.com/aquasecurity/tfsec) to make sure that potential security risks are found. TfSec is a static code analysis tool.

## Migrations required

No

## Verification

Check that the action is started for a PR.

### CODE REVIEW

**Comment by kayman-mk** [comment]
@npalm What do you think about static code analysis? The workflow needs a `${{ github.token }}` to be able to comment on a PR.

**Comment by kayman-mk** [comment]
Following issues were found:

```
Log group is not encrypted. .... not writing as not part of the current PR
Log group is not encrypted. .... not writing as not part of the current PR
Security group rule allows egress to multiple public internet addresses. .... not writing as not part of the current PR
Security group rule allows egress to multiple public internet addresses. .... not writing as not part of the current PR
Security group rule allows egress to multiple public internet addresses. .... not writing as not part of the current PR
Security group rule allows egress to multiple public internet addresses. .... not writing as not part of the current PR
Security group rule allows egress to multiple public internet addresses. .... not writing as not part of the current PR
Security group rule allows egress to multiple public internet addresses. .... not writing as not part of the current PR
Security group rule allows egress to multiple public internet addresses. .... not writing as not part of the current PR
Security group rule allows egress to multiple public internet addresses. .... not writing as not part of the current PR
IAM policy document uses sensitive action 'logs:PutLogEvents' on wildcarded resource 'cfc4dcb2-618a-4f60-b6[48](https://github.com/npalm/terraform-aws-gitlab-runner/runs/8023472057?check_suite_focus=true#step:4:49)-12223ed9935a:*' .... not writing as not part of the current PR
IAM policy document uses sensitive action 'logs:PutLogEvents' on wildcarded resource 'cfc4dcb2-618a-4f[60](https://github.com/npalm/terraform-aws-gitlab-runner/runs/8023472057?check_suite_focus=true#step:4:61)-b648-12223ed9935a:*' .... not writing as not part of the current PR
IAM policy document uses sensitive action 'logs:PutLogEvents' on wildcarded resource 'cfc4dcb2-[61](https://github.com/npalm/terraform-aws-gitlab-runner/runs/8023472057?check_suite_focus=true#step:4:62)8a-4f60-b648-12223ed9935a:*' .... not writing as not part of the current PR
IAM policy document uses sensitive action 'logs:PutLogEvents' on wildcarded resource 'cfc4dcb2-618a-4f60-b648-12223ed9935a:*' .... not writing as not part of the current PR
IAM policy document uses sensitive action 'ec2:TerminateInstances' on wildcarded resource '*' .... not writing as not part of the current PR
IAM policy document uses sensitive action 'ec2:TerminateInstances' on wildcarded resource '*' .... not writing as not part of the current PR
Function does not have tracing enabled. .... not writing as not part of the current PR
Bucket does not have logging enabled .... not writing as not part of the current PR
Bucket does not have versioning enabled .... not writing as not part of the current PR
Bucket does not encrypt data with a customer managed key. .... not writing as not part of the current PR
```

If you decide to go for it, I will create another PR to fix the issues.

**Comment by npalm** [comment]
Will merge this this week, in a separate branch, to see the impact on CI.

**Review by npalm — APPROVED** [review]

**Comment by npalm** [comment]
Just merge to develop, thanks

**Pull request merged**
