### PR TITLE
feat: add metadata options for AWS 4.x provider

### PR DESCRIPTION
**Pull request by kayman-mk**
## Description

Updates the docker-machine to newest version to be able to add options for `amazonec2-metadata-token` and `amazonec2-metadata-token-response-hop-limit`. Both options are set by default.

Typical error message is
```
| Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│ 
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│ 
│ Error: no EC2 IMDS role found, operation error ec2imds: GetMetadata, canceled, context deadline exceeded
```

Refer to https://github.com/hashicorp/terraform-provider-aws/issues/23110 for a discussion about the changes introduced with the AWS 4.x provider.

## Migrations required

Make sure that you do not specify the `docker_machine_download_url` and that you also not specify the above mentioned options in the `docker_machine_options`. If you do so, remove them.

If you have to use a special download url, make sure that the new options are supported by that version.

## Verification

Installed the new module in our CI/CD system for manual checks. Looks good so far.
Also checked the `config.toml` for no `docker_machine_options`. Looks good too.

## Documentation

We use [pre-commit](https://pre-commit.com/) to update the Terraform inputs and outputs in the documentation via [terraform-docs](https://github.com/terraform-docs/terraform-docs). Ensure you have installed those components.

### CODE REVIEW

**Comment by npalm** [comment]
@kayman-mk great work, we also have another PR open #444 Would prefer to merge the 4.x work together and relase. In the mean time I will check the veriosn.tf and lock the provider to 3* (before merging). Will check the PR this weekend

**Comment by kayman-mk** [comment]
rebased

**Comment by npalm** [comment]
@kayman-mk Looks like this was added the latest gitlab release of docker machine (10 months ago). Can you run another rebase. 

In the PR title you refer to AWS provider 4.0. What is the relation? As far i can't see there is norelation.

**Comment by kayman-mk** [comment]
Updated one of my runners to 4.41.1 Working without any problems. Seems that this fix might be superfluous.

**Comment by sanjeevmagoo** [comment]
ok

**Review by npalm — COMMENTED** [review]
LGTM, need to test

**Comment by npalm** [comment]
@kayman-mk first of all, sorry for keep you waiting so long. Had some travels and got finally ill :( 

Just tested the PR. Hoever the change looks goot and options seems to be supported no docker-machine is crated. I used the default example to test. With latest gitlab runner and docker machine version (gitlab one). 

I have tested the PR on top of #460 which enables the terraform 4 provider. Without the PR the Terraform 4 provider works fine for mee. Build runners are crated as normal. 

Any idea what could be wrong? Do you have time to check the change on top of the PR with the default example.

**Comment by npalm** [comment]
@kayman-mk seems I missed this PR in #460 please can you have a quick lock the conflicts?

**Comment by npalm** [comment]
@kayman-mk testing a solution based on the PR right now, looks good so far.  Keep you updated

**Comment by npalm** [comment]
Created a PR on top of #460  to add metadata options for docker machine, based on this PR

see https://github.com/npalm/terraform-aws-gitlab-runner/pull/490

**Comment by npalm** [comment]
Thanks a lot for you help, all work is nog back on develop. You are refered in the the commits as co-author!

**Pull request closed without merging**
