### PR TITLE
Update Gitlab Runner to 11.3.1

### PR DESCRIPTION
**Pull request by Vad1mo**
I updated the default config for the runner to 11.3.1, The Markdown linter kicked in and I decided to fix some typos and make the markdown a bit better readable.

### CODE REVIEW

**Comment by npalm** [comment]
Thanks for the PR, will check the PR in the next days

**Comment by npalm** [comment]
@Vad1mo Just wondering, which tool do you use to generate the markdown overview of the variables and output?

**Comment by Vad1mo** [comment]
I use Visual Studio Code with the [prettier](https://github.com/prettier/prettier) extension and [markdownlint](https://github.com/DavidAnson/markdownlint)

both tools can also be used in the CI pipeline as they are available as NPM packages.

**Comment by npalm** [comment]
Thanks

**Pull request merged**
