### PR TITLE
docs: detail the usage of S3 cache policy

### PR DESCRIPTION
**Pull request by kayman-mk**
## Description

As explained in #410 and #426 additional documentation is needed for
- permissions needed to access the S3 cache. This is configured on the Runner instance and not on the Executor (as I thought too). But the documentation tolds a different story.

## Migrations required

No

## Verification

Just some comments. No verification done.

### CODE REVIEW

**Comment by kayman-mk** [comment]
This is a copy of #427 which was merged by accident into the `develop` branch.

@npalm Please approve.

**Comment by kayman-mk** [comment]
Failing workflow is tackled in #604

**Review by npalm — APPROVED** [review]

**Comment by npalm** [comment]
Can you you shortly explain why pre_install and post_intall are not working for you? With those variables you can inject already scripts in the before and after installation.

**Comment by kayman-mk** [comment]
> Can you you shortly explain why pre_install and post_intall are not working for you? With those variables you can inject already scripts in the before and after installation.

@npalm I didn't get the point here as a single comment was added only. Is this the right PR for the comment? If so, could you please give some more information please?

**Pull request merged**
