### PR TITLE
471 add AuthenticationType

### PR DESCRIPTION
**Pull request by gravitybacklight**
## Description

One method to support adding AuthenticationType = "IAM" whilst ensuring no changes to configuration for earlier versions.
Only adds it in if the major version of the runner is 15 or higher.

## Migrations required

NO

## Verification

Tested with versions 14 & 15 to confirm the user-data only sees this change if version 15.

### CODE REVIEW

**Comment by kayman-mk** [comment]
Not 100% clear what problem is solved in this PR. What is the problem with the default value?

According to the docs
>   In GitLab 14.4 and later, set to iam or access-key. Default is access-key if ServerAddress, AccessKey, and SecretKey are all provided. Defaults to iam if ServerAddress, AccessKey, or SecretKey are missing.

**Comment by kayman-mk** [comment]
Got it, explained in #471 It becomes a mandatory parameter.

**Comment by gravitybacklight** [comment]
@kayman-mk yeah, I was unsure if there was any use case of an access key for this module, but if not, it can just be hardcoded as `AuthenticationType = "IAM"`

**Comment by kayman-mk** [comment]
I think the Runners and Executors usw instance profiles only. So hardcoding the value looks good to me.

**Comment by kayman-mk** [comment]
You are right. It's the better solution.

**Review by npalm — APPROVED** [review]
@gravitybacklight thanks for your work, sorry for the far too late reply. Will merge the change in a temporay branch and apply some extra fixes..

**Pull request merged**
